include /etc/nginx/geo_trusted.conf;

server {
    listen 80;

    location / {
        proxy_set_header X-Forwarded-For $xff_value;
        proxy_set_header Host $host;
        proxy_pass http://172.20.0.13:80;
    }
}
